

# Setup
title:            Big Prime Numbers
tagline:          'Portfolio, Blogging, Coding, Design, Development'
url:              http://www.bigprimenumbers.com
shorturl:         bigprimenumbers.com


author:
  name:           'Michael Phelan'
  url:            https://twitter.com/joshualande
  email:          phelan.map@gmail.com

# Custom vars
version:          1.0.0

github:
  repo:           github.com/bigprimenumbersdotcom/bigprimenumbersdotcom.github.io