
destination: public
source: src

# Setup
title: Big Prime Numbers
tagline: 'Blogging, Coding, Design, Development'
url: http://www.bigprimenumbers.com
shorturl: bigprimenumbers.com


author:
  name: 'Michael Phelan'
  email: phelan.map@gmail.com

# Custom vars
version: 1.0.0

sass:
  sass_dir: src/_scss
  style: compressed

github:
  repo: github.com/bigprimenumbersdotcom/bigprimenumbersdotcom.github.io

exclude: ["node_modules"]

gems:
  - jekyll-redirect-from
